// frontend_vue/src/components/FilterBar.vue
<script setup>
import { computed } from 'vue'

const props = defineProps({
  filterMeta: { type: Object, default: () => ({}) },
  modelValue: { type: Object, default: () => ({ start_date: null, end_date: null, region: null, category: null }) },
})
const emit = defineEmits(['update:modelValue', 'apply', 'reset'])

const regions = computed(() => props.filterMeta.regions || [])
const categories = computed(() => props.filterMeta.categories || [])

function update(key, e) {
  const v = e.target.value || null
  emit('update:modelValue', { ...props.modelValue, [key]: v })
}
</script>

<template>
  <header class="filter-bar">
    <label>Start</label>
    <input type="date" :value="modelValue.start_date" @input="update('start_date', $event)" />
    <label>End</label>
    <input type="date" :value="modelValue.end_date" @input="update('end_date', $event)" />
    <label>Region</label>
    <select :value="modelValue.region || ''" @change="update('region', $event)">
      <option value="">All Regions</option>
      <option v-for="r in regions" :key="r" :value="r">{{ r }}</option>
    </select>
    <label>Category</label>
    <select :value="modelValue.category || ''" @change="update('category', $event)">
      <option value="">All Categories</option>
      <option v-for="c in categories" :key="c" :value="c">{{ c }}</option>
    </select>
    <button class="primary" @click="$emit('apply')">Apply</button>
    <button @click="$emit('reset')">Reset</button>
  </header>
</template>

// frontend_react/src/components/FilterBar.jsx
import React from 'react'

export default function FilterBar({ filterMeta, filters, onFilterChange, onApply, onReset }) {
  const regions = filterMeta?.regions || []
  const categories = filterMeta?.categories || []

  const update = (key, e) => onFilterChange({ ...filters, [key]: e.target.value || null })

  return (
    <header className="filter-bar">
      <label>Start</label>
      <input type="date" value={filters.start_date || ''} onChange={e => update('start_date', e)} />
      <label>End</label>
      <input type="date" value={filters.end_date || ''} onChange={e => update('end_date', e)} />
      <label>Region</label>
      <select value={filters.region || ''} onChange={e => update('region', e)}>
        <option value="">All Regions</option>
        {regions.map(r => <option key={r} value={r}>{r}</option>)}
      </select>
      <label>Category</label>
      <select value={filters.category || ''} onChange={e => update('category', e)}>
        <option value="">All Categories</option>
        {categories.map(c => <option key={c} value={c}>{c}</option>)}
      </select>
      <button className="primary" onClick={onApply}>Apply</button>
      <button onClick={onReset}>Reset</button>
    </header>
  )
}
