// frontend_vue/src/components/SidebarNav.vue
<script setup>
import { useRoute } from 'vue-router'

const route = useRoute()
</script>

<template>
  <aside class="sidebar">
    <router-link to="/" class="sidebar-logo">
      Superstore
      <span>Analytics Dashboard</span>
    </router-link>
    <nav>
      <router-link to="/">
        <span style="font-size:16px;width:20px;text-align:center">&#9633;</span>
        Dashboard
      </router-link>
      <router-link to="/ai">
        <span style="font-size:16px;width:20px;text-align:center">&#10041;</span>
        AI Analysis
      </router-link>
    </nav>
  </aside>
</template>

// frontend_react/src/components/SidebarNav.jsx
import React from 'react'
import { NavLink } from 'react-router-dom'

export default function SidebarNav() {
  return (
    <aside className="sidebar">
      <NavLink to="/" className="sidebar-logo">
        Superstore
        <span>Analytics Dashboard</span>
      </NavLink>
      <nav>
        <NavLink to="/">
          <span style={{ fontSize: '16px', width: '20px', textAlign: 'center' }}>&#9633;</span>
          Dashboard
        </NavLink>
        <NavLink to="/ai">
          <span style={{ fontSize: '16px', width: '20px', textAlign: 'center' }}>&#10041;</span>
          AI Analysis
        </NavLink>
      </nav>
    </aside>
  )
}
